Bump the iplocation group in /iplocation with 4 updates (#521)
Bumps the iplocation group in /iplocation with 4 updates:
[axios](https://github.com/axios/axios),
[axios-retry](https://github.com/softonic/axios-retry),
[@types/node](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/node)
and
[@types/react](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/HEAD/types/react).

Updates `axios` from 1.7.4 to 1.7.7
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/axios/axios/releases">axios's
releases</a>.</em></p>
<blockquote>
<h2>Release v1.7.7</h2>
<h2>Release notes:</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>fetch:</strong> fix stream handling in Safari by fallback to
using a stream reader instead of an async iterator; (<a
href="https://redirect.github.com/axios/axios/issues/6584">#6584</a>)
(<a
href="https://github.com/axios/axios/commit/d1980854fee1765cd02fa0787adf5d6e34dd9dcf">d198085</a>)</li>
<li><strong>http:</strong> fixed support for IPv6 literal strings in url
(<a
href="https://redirect.github.com/axios/axios/issues/5731">#5731</a>)
(<a
href="https://github.com/axios/axios/commit/364993f0d8bc6e0e06f76b8a35d2d0a35cab054c">364993f</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a href="https://github.com/Rishi556"
title="+39/-1 ([#5731](https://github.com/axios/axios/issues/5731)
)">Rishi556</a></li>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+27/-7
([#6584](https://github.com/axios/axios/issues/6584) )">Dmitriy
Mozgovoy</a></li>
</ul>
<h2>Release v1.7.6</h2>
<h2>Release notes:</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>fetch:</strong> fix content length calculation for FormData
payload; (<a
href="https://redirect.github.com/axios/axios/issues/6524">#6524</a>)
(<a
href="https://github.com/axios/axios/commit/085f56861a83e9ac02c140ad9d68dac540dfeeaa">085f568</a>)</li>
<li><strong>fetch:</strong> optimize signals composing logic; (<a
href="https://redirect.github.com/axios/axios/issues/6582">#6582</a>)
(<a
href="https://github.com/axios/axios/commit/df9889b83c2cc37e9e6189675a73ab70c60f031f">df9889b</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+98/-46
([#6582](https://github.com/axios/axios/issues/6582) )">Dmitriy
Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/jacquesg"
title="+5/-1 ([#6524](https://github.com/axios/axios/issues/6524)
)">Jacques Germishuys</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/kuroino721"
title="+3/-1 ([#6575](https://github.com/axios/axios/issues/6575)
)">kuroino721</a></li>
</ul>
<h2>Release v1.7.5</h2>
<h2>Release notes:</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>adapter:</strong> fix undefined reference to hasBrowserEnv
(<a
href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>)
(<a
href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1">7004707</a>)</li>
<li><strong>core:</strong> add the missed implementation of
AxiosError#status property; (<a
href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)
(<a
href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852">6700a8a</a>)</li>
<li><strong>core:</strong> fix <code>ReferenceError: navigator is not
defined</code> for custom environments; (<a
href="https://redirect.github.com/axios/axios/issues/6567">#6567</a>)
(<a
href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794">fed1a4b</a>)</li>
<li><strong>fetch:</strong> fix credentials handling in Cloudflare
workers (<a
href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>)
(<a
href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d">550d885</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+187/-83
([#6573](https://github.com/axios/axios/issues/6573)
[#6567](https://github.com/axios/axios/issues/6567)
[#6566](https://github.com/axios/axios/issues/6566)
[#6564](https://github.com/axios/axios/issues/6564)
[#6563](https://github.com/axios/axios/issues/6563)
[#6557](https://github.com/axios/axios/issues/6557)
[#6556](https://github.com/axios/axios/issues/6556)
[#6555](https://github.com/axios/axios/issues/6555)
[#6554](https://github.com/axios/axios/issues/6554)
[#6552](https://github.com/axios/axios/issues/6552) )">Dmitriy
Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/antoninbas"
title="+6/-6 ([#6572](https://github.com/axios/axios/issues/6572)
)">Antonin Bas</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/hansottowirtz"
title="+4/-1 ([#6533](https://github.com/axios/axios/issues/6533)
)">Hans Otto Wirtz</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/axios/axios/blob/v1.x/CHANGELOG.md">axios's
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/axios/axios/compare/v1.7.6...v1.7.7">1.7.7</a>
(2024-08-31)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>fetch:</strong> fix stream handling in Safari by fallback to
using a stream reader instead of an async iterator; (<a
href="https://redirect.github.com/axios/axios/issues/6584">#6584</a>)
(<a
href="https://github.com/axios/axios/commit/d1980854fee1765cd02fa0787adf5d6e34dd9dcf">d198085</a>)</li>
<li><strong>http:</strong> fixed support for IPv6 literal strings in url
(<a
href="https://redirect.github.com/axios/axios/issues/5731">#5731</a>)
(<a
href="https://github.com/axios/axios/commit/364993f0d8bc6e0e06f76b8a35d2d0a35cab054c">364993f</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a href="https://github.com/Rishi556"
title="+39/-1 ([#5731](https://github.com/axios/axios/issues/5731)
)">Rishi556</a></li>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+27/-7
([#6584](https://github.com/axios/axios/issues/6584) )">Dmitriy
Mozgovoy</a></li>
</ul>
<h2><a
href="https://github.com/axios/axios/compare/v1.7.5...v1.7.6">1.7.6</a>
(2024-08-30)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>fetch:</strong> fix content length calculation for FormData
payload; (<a
href="https://redirect.github.com/axios/axios/issues/6524">#6524</a>)
(<a
href="https://github.com/axios/axios/commit/085f56861a83e9ac02c140ad9d68dac540dfeeaa">085f568</a>)</li>
<li><strong>fetch:</strong> optimize signals composing logic; (<a
href="https://redirect.github.com/axios/axios/issues/6582">#6582</a>)
(<a
href="https://github.com/axios/axios/commit/df9889b83c2cc37e9e6189675a73ab70c60f031f">df9889b</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+98/-46
([#6582](https://github.com/axios/axios/issues/6582) )">Dmitriy
Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/jacquesg"
title="+5/-1 ([#6524](https://github.com/axios/axios/issues/6524)
)">Jacques Germishuys</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/kuroino721"
title="+3/-1 ([#6575](https://github.com/axios/axios/issues/6575)
)">kuroino721</a></li>
</ul>
<h2><a
href="https://github.com/axios/axios/compare/v1.7.4...v1.7.5">1.7.5</a>
(2024-08-23)</h2>
<h3>Bug Fixes</h3>
<ul>
<li><strong>adapter:</strong> fix undefined reference to hasBrowserEnv
(<a
href="https://redirect.github.com/axios/axios/issues/6572">#6572</a>)
(<a
href="https://github.com/axios/axios/commit/7004707c4180b416341863bd86913fe4fc2f1df1">7004707</a>)</li>
<li><strong>core:</strong> add the missed implementation of
AxiosError#status property; (<a
href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)
(<a
href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852">6700a8a</a>)</li>
<li><strong>core:</strong> fix <code>ReferenceError: navigator is not
defined</code> for custom environments; (<a
href="https://redirect.github.com/axios/axios/issues/6567">#6567</a>)
(<a
href="https://github.com/axios/axios/commit/fed1a4b2d78ed4a588c84e09d32749ed01dc2794">fed1a4b</a>)</li>
<li><strong>fetch:</strong> fix credentials handling in Cloudflare
workers (<a
href="https://redirect.github.com/axios/axios/issues/6533">#6533</a>)
(<a
href="https://github.com/axios/axios/commit/550d885eb90fd156add7b93bbdc54d30d2f9a98d">550d885</a>)</li>
</ul>
<h3>Contributors to this release</h3>
<ul>
<li><!-- raw HTML omitted --> <a
href="https://github.com/DigitalBrainJS" title="+187/-83
([#6573](https://github.com/axios/axios/issues/6573)
[#6567](https://github.com/axios/axios/issues/6567)
[#6566](https://github.com/axios/axios/issues/6566)
[#6564](https://github.com/axios/axios/issues/6564)
[#6563](https://github.com/axios/axios/issues/6563)
[#6557](https://github.com/axios/axios/issues/6557)
[#6556](https://github.com/axios/axios/issues/6556)
[#6555](https://github.com/axios/axios/issues/6555)
[#6554](https://github.com/axios/axios/issues/6554)
[#6552](https://github.com/axios/axios/issues/6552) )">Dmitriy
Mozgovoy</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/antoninbas"
title="+6/-6 ([#6572](https://github.com/axios/axios/issues/6572)
)">Antonin Bas</a></li>
<li><!-- raw HTML omitted --> <a href="https://github.com/hansottowirtz"
title="+4/-1 ([#6533](https://github.com/axios/axios/issues/6533)
)">Hans Otto Wirtz</a></li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/axios/axios/commit/5b8a826771b77ab30081d033fdba9ef3b90e439a"><code>5b8a826</code></a>
chore(release): v1.7.7 (<a
href="https://redirect.github.com/axios/axios/issues/6585">#6585</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/364993f0d8bc6e0e06f76b8a35d2d0a35cab054c"><code>364993f</code></a>
fix(http): fixed support for IPv6 literal strings in url (<a
href="https://redirect.github.com/axios/axios/issues/5731">#5731</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/d1980854fee1765cd02fa0787adf5d6e34dd9dcf"><code>d198085</code></a>
fix(fetch): fix stream handling in Safari by fallback to using a stream
reade...</li>
<li><a
href="https://github.com/axios/axios/commit/d584fcfa62ba5217baf2be0748b7c5eda6da16ad"><code>d584fcf</code></a>
chore(release): v1.7.6 (<a
href="https://redirect.github.com/axios/axios/issues/6583">#6583</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/bc03c6cbc41eb8449daa2f4b6b8048671a05bded"><code>bc03c6c</code></a>
chore(examples): fix module import (<a
href="https://redirect.github.com/axios/axios/issues/6575">#6575</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/df9889b83c2cc37e9e6189675a73ab70c60f031f"><code>df9889b</code></a>
fix(fetch): optimize signals composing logic; (<a
href="https://redirect.github.com/axios/axios/issues/6582">#6582</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/ee208cfcae8770ac579f26e7278867567886e026"><code>ee208cf</code></a>
chore(sponsor): update sponsor block (<a
href="https://redirect.github.com/axios/axios/issues/6576">#6576</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/085f56861a83e9ac02c140ad9d68dac540dfeeaa"><code>085f568</code></a>
fix(fetch): fix content length calculation for FormData payload; (<a
href="https://redirect.github.com/axios/axios/issues/6524">#6524</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/59cd6b0dece4050b190717a7c5cdf77906ce2104"><code>59cd6b0</code></a>
chore(release): v1.7.5 (<a
href="https://redirect.github.com/axios/axios/issues/6574">#6574</a>)</li>
<li><a
href="https://github.com/axios/axios/commit/6700a8adac06942205f6a7a21421ecb36c4e0852"><code>6700a8a</code></a>
fix(core): add the missed implementation of AxiosError#status property;
(<a
href="https://redirect.github.com/axios/axios/issues/6573">#6573</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/axios/axios/compare/v1.7.4...v1.7.7">compare
view</a></li>
</ul>
</details>
<br />

Updates `axios-retry` from 4.4.2 to 4.5.0
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/softonic/axios-retry/blob/master/CHANGELOG.md">axios-retry's
changelog</a>.</em></p>
<blockquote>
<h2>[4.5.0] - 2024-08-02</h2>
<ul>
<li>added linearDelay function</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/softonic/axios-retry/commit/4c38b77bce745f6d077a55c5ac02aafe9be72dc1"><code>4c38b77</code></a>
New version: 4.5.0</li>
<li><a
href="https://github.com/softonic/axios-retry/commit/1ce441ae2a15eb239ccb8c047be94f16070f714f"><code>1ce441a</code></a>
update CHANGELOG</li>
<li><a
href="https://github.com/softonic/axios-retry/commit/ef0096772b9030664ffeda868ccdd204ea642fb4"><code>ef00967</code></a>
Merge pull request <a
href="https://redirect.github.com/softonic/axios-retry/issues/285">#285</a>
from yutak23/feature/add-linearDelay</li>
<li><a
href="https://github.com/softonic/axios-retry/commit/756dd7bbf1d0106f64903ca8563de27747c5efa0"><code>756dd7b</code></a>
feat: add linearDelay for retryDelay option</li>
<li>See full diff in <a
href="https://github.com/softonic/axios-retry/compare/v4.4.2...v4.5.0">compare
view</a></li>
</ul>
</details>
<br />

Updates `@types/node` from 22.0.2 to 22.5.2
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/node">compare
view</a></li>
</ul>
</details>
<br />

Updates `@types/react` from 18.3.3 to 18.3.5
<details>
<summary>Commits</summary>
<ul>
<li>See full diff in <a
href="https://github.com/DefinitelyTyped/DefinitelyTyped/commits/HEAD/types/react">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>